spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

app:
  secret-key: 4F9A93E69886ED229F3494237EDD1BD18E4E56B9FC73121A1A122C8A2957D771
  jwt-expiration-ms: 86400000 # 1 day